name: Emscripten

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup emsdk
      uses: mymindstorm/setup-emsdk@v5
      with:
        version: latest-upstream
        actions-cache-folder: 'emsdk-cache'

    - name: Build with Emscripten
      run: |
        cd workspaces/cmake/
        python3 build_emscripten.py
