name: Emscripten

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v5
        with:
          version: latest-upstream
          actions-cache-folder: 'emsdk-cache'
         
      - name: Load emsdk env
        run: source emsdk-cache/emsdk-master/emsdk_env.sh
        
      - name: Print Env
        run: printenv

      - name: Build with Emscripten
        run: |
          cd workspaces/cmake/
          python3 build_emscripten.py
