name: IOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2

      - name: Xcode version
        run: /usr/bin/xcodebuild -version
             
      - name: Create assets dir
        run: mkdir project/assets
             
      - name: Build with Xcode
        run: |
          cd workspaces/xcode/
          xcodebuild build -sdk iphonesimulator -project Supernova.xcodeproj -configuration Debug -scheme supernova-ios
