name: IOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2

      - name: Xcode version
        run: /usr/bin/xcodebuild -version
        
      - name: Build archive
        run: |
          export DEVELOPMENT_TEAM="xxxxx"
          cd workspaces/xcode/
          xcodebuild build -sdk iphoneos -project Supernova.xcodeproj \
            -configuration Debug -scheme supernova-ios
