name: IOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2

      - name: Xcode version
        run: /usr/bin/xcodebuild -version
        
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_11.5.app
             
      - name: Build archive
        env:
          DEVELOPER_DIR: /Applications/Xcode_11.5.app/Contents/Developer
        run: |
          cd workspaces/xcode/
          xcodebuild -sdk iphoneos -project Supernova.xcodeproj -configuration Release -scheme supernova-ios -derivedDataPath DerivedData -archivePath DerivedData/Archive/Supernova archive
